services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - /data/mongodb:/data/db

# MongoDB commands
# 1. mongosh mongodb://localhost:27017
# 2. show dbs
# 3. use <db_name>
# 4. show collections
# 5. db.<collection_name>.find()
# 6. db.<collection_name>.find().pretty()